#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 31 14:41:56 2021

@author: berkanttubi
"""

from selenium import webdriver 
import time

browser= webdriver.Firefox()

url = "https://tureng.com/en/turkish-english"
browser.get(url)

word = input("Enter the word: ")

searchBar= browser.find_element_by_xpath("//*[@id='searchTerm']")
searchBar.send_keys(word)

ara= browser.find_element_by_css_selector('input.btn:nth-child(5)')

ara.click()

elements= browser.find_element_by_xpath("//*[@id='englishResultsTable']")

print(elements.text)
